const constants = {
  REDUCER_ROOT: 'search',

  CAMPAIGN_RESULTS_LOADING: 'app/SearchPage/CAMPAIGN_RESULTS_LOADING',
  ARTIST_RESULTS_LOADING: 'app/SearchPage/ARTIST_RESULTS_LOADING',
  VENUE_RESULTS_LOADING: 'app/SearchPage/VENUE_RESULTS_LOADING',
  OPPORTUNITY_RESULTS_LOADING: 'app/SearchPage/OPPORTUNITY_RESULTS_LOADING',
  OPEN_SHOW_RESULTS_LOADING: 'app/SearchPage/OPEN_SHOW_RESULTS_LOADING',
  OPEN_MIC_RESULTS_LOADING: 'app/SearchPage/OPEN_MIC_RESULTS_LOADING',
  USER_ACTS_LOADING: 'app/SearchPage/USER_ACTS_LOADING',

  BAND_RESULTS_LOADED: 'app/SearchPage/BAND_RESULTS_LOADED',
  CAMPAIGN_RESULTS_LOADED: 'app/SearchPage/CAMPAIGN_RESULTS_LOADED',
  VENUE_RESULTS_LOADED: 'app/SearchPage/VENUE_RESULTS_LOADED',
  OPPORTUNITY_RESULTS_LOADED: 'app/SearchPage/OPPORTUNITY_RESULTS_LOADED',
  OPEN_SHOW_RESULTS_LOADED: 'app/SearchPage/OPEN_SHOW_RESULTS_LOADED',
  OPEN_MIC_RESULTS_LOADED: 'app/SearchPage/OPEN_MIC_RESULTS_LOADED',
  USER_ACTS_LOADED: 'app/SearchPage/USER_ACTS_LOADED',
  SEARCH_ERROR: 'app/SearchPage/SEARCH_ERROR',

  OPPORTUNITY_APPLIED_SUCCESS: 'You have applied to play! Visit the Show Hub for this event to discuss details, which can be found via "My Shows".'
}

export default constants