const constants = {
  REDUCER_ROOT: 'home',

  LOAD_DATA_START: 'app/Home/LOAD_DATA_START',
  OPENINGS_LOADED: 'app/Home/OPENINGS_LOADED',
  FEATURED_BANDS_LOADED: 'app/Home/FEATURED_BANDS_LOADED',
  FEATURED_CAMPAIGNS_LOADED: 'app/Home/FEATURED_CAMPAIGNS_LOADED',
  FEATURED_VENUES_LOADED: 'app/Home/FEATURED_VENUES_LOADED',
  PREVIOUSLY_SUCCESSFUL_LOADED: 'app/Home/PREVIOUSLY_SUCCESSFUL_LOADED',
  VENUE_LOADED: 'app/Home/VENUE_LOADED',
  CAMPAIGN_LOADED: 'app/Home/CAMPAIGN_LOADED'
}

export default constants