const constants = {
  REDUCER_ROOT: 'login',

  SUBMIT: 'redpine/Login/SUBMIT',
  ALPHA_USER: 'redpine/Login/ALPHA_USER',
  UPDATE_FORM: 'redpine/Login/UPDATE_FORM',
  LOGIN_SUCCESS: 'redpine/Login/LOGIN_SUCCESS',
  LOGIN_ERROR: 'redpine/Login/LOGIN_ERROR',
  START_FACEBOOK_LOGIN: 'redpine/Login/START_FACEBOOK_LOGIN',
  VALIDATE_FACEBOOK_TOKEN_START: 'redpine/Login/VALIDATE_FACEBOOK_TOKEN_START',
  VALIDATE_FACEBOOK_TOKEN_ERROR: 'redpine/Login/VALIDATE_FACEBOOK_TOKEN_ERROR',
  VALIDATE_FACEBOOK_TOKEN_SUCCESS: 'redpine/Login/VALIDATE_FACEBOOK_TOKEN_SUCCESS'
}

export default constants