const constants = {
  REDUCER_ROOT: 'app',

  SET_AUTH: 'redpine/App/SET_AUTH',
  USER_LOADING: 'redpine/App/USER_LOADING',
  SET_USER: 'redpine/App/SET_USER',
  SET_SETTINGS: 'redpine/App/SET_SETTINGS',
  SET_REDIRECT: 'redpine/App/SET_REDIRECT',
  SEND_NOTIFICATION: 'redpine/App/SEND_NOTIFICATION',
  CLEAR_NOTIFICATION: 'redpine/App/CLEAR_NOTIFICATION',
  ADD_BODY_CLICK_HANDLER: 'redpine/App/ADD_BODY_CLICK_HANDLER',
  HELP_TOPIC: 'redpine/App/HELP_TOPIC',
  SHOW_BUY_REDPINE: 'redpine/App/SHOW_BUY_REDPINE',
  HIDE_BUY_REDPINE: 'redpine/App/HIDE_BUY_REDPINE',
  REMOVE_BODY_CLICK_HANDLER: 'redpine/App/REMOVE_BODY_CLICK_HANDLER',
  SET_SPOTIFY_CONNECTION: 'redpine/App/SET_SPOTIFY_CONNECTION',
  USERS_LOADED: 'redpine/App/USERS_LOADED',
  CITIES_LOADED: 'redpine/App/CITIES_LOADED',
  VENUE_CITIES_LOADED: 'redpine/App/VENUE_CITIES_LOADED',
  ACT_CITIES_LOADED: 'redpine/App/ACT_CITIES_LOADED',
  PROVINCES_LOADED: 'redpine/App/PROVINCES_LOADED',
  COUNTRIES_LOADED: 'redpine/App/COUNTRIES_LOADED',
  GENRES_LOADED: 'redpine/App/GENRES_LOADED',
  SHOW_NAVJUMP: 'redpine/App/SHOW_NAVJUMP',
  HIDE_NAVJUMP: 'redpine/App/HIDE_NAVJUMP'
}

export default constants