const constants = {
  REDUCER_ROOT: 'search',

  CAMPAIGN_RESULTS_LOADING: 'app/SearchPage/CAMPAIGN_RESULTS_LOADING',
  OPEN_SHOW_RESULTS_LOADING: 'app/SearchPage/OPEN_SHOW_RESULTS_LOADING',

  CAMPAIGN_RESULTS_LOADED: 'app/SearchPage/CAMPAIGN_RESULTS_LOADED',
  OPEN_SHOW_RESULTS_LOADED: 'app/SearchPage/OPEN_SHOW_RESULTS_LOADED',
  SEARCH_ERROR: 'app/SearchPage/SEARCH_ERROR'
}

export default constants